# Generated by Django 4.1.2 on 2022-11-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_primary_contact',
            new_name='client_company',
        ),
    ]
