# Generated by Django 4.1.2 on 2022-12-01 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_client_primary_contact_client_client_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('parent_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.task')),
                ('task_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.project')),
            ],
        ),
    ]
